### ISSUE TITLE
Current ToDo

### ISSUE THREAD

**Issue by straussmaximilian** [MannLabs/alphapept#1]
# Things that need to be done for the Alpha Release (v.0.4.0)

## Major
- [x] DIA library export
- [x] **Upgrade GPU FF to CPU**
- [x] **Include GPU CI/CD**
- [x] Test unspecific search again

## Minor Bugs
- [x] Unknown AAs -> What to do with this? 
- [x] Update Runner notebooks

## Stability
- [x] Include a check that when running a workflow the requirements are met

## Bugs
- [x] Revise Quantification (@jalew188, @straussmaximilian ) -> Upgrade split level
- [x] Bug in Testrunner 2020-10-26 00:18:05 INFO - Numba version 0.50.1 -> Something is wrong here

## GUI
- [x] Make check settings button usable (i.e. this setting needs to be changed) or remove
- [x] Fix speed issue (why is process slower than cmd) #116 
- [x] Get FileWatcher to work again
- [x] Fix progress bar 
- [x] Make data preview happen in GUI again

## Installer
**- [ ] Loading of ext does not work -> Check installed version
- [x] Auto upload for proper release cycle**

## Due Diligence
- [x] Go over Documentation
- [x] Check that all settings are being used
- [x] Revise logging output
- [x] Revise naming convention (peptides / precursors / psms, m_offset <> m_tol -> ms1_tolerance, ms2_tolerance)
- [x] Version: When are we calling what? __version__ ? 
- [x] Clean up Performance plots
- [x] Clean up Git Config
- [x] Clean up Branches

## CI / CD
- [x] CI Test for Windows, Linux and Mac #134 
- [x] Perform Integration Test
- [x] Include Styleguide Tests

# Future

## Features
- [x] PTM Support #39 
## Code Stability
- [x] Test Coverage
- [x] Include Bound checks in functions to make usage more stable (i.e. error when having negative intensity) #58 

## Isobaric Labels
- [x] TMT <> EasiTag <> Silac
- [x] Second Peptide Search: Shared fragments etc

## Quantification
- [x] Constantins Quantification

## Performance
- [x] Optimal parameters for Bruker FF
- [x] Speed up CLI
